# Generated by Django 3.2.13 on 2022-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20220527_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='curr_user',
            new_name='curr_user1',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='dest_user',
            new_name='dest_user1',
        ),
    ]
