# Generated by Django 3.2.13 on 2022-05-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20220527_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='account_type',
            new_name='account_type1',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='account_type2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='accounttransfer1', to='banking.bankaccount'),
            preserve_default=False,
        ),
    ]
