# Generated by Django 3.2.13 on 2022-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20220527_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneytransfer',
            options={},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type1',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type2',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='account_type1',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='account_type2',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='curr_user1',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='dest_user1',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='EmailCur',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='EmailDes',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
